Update plexupdate

diff --git a/plexupdate b/plexupdate
--- a/plexupdate
+++ b/plexupdate
@@ -1,9 +1,8 @@
 #!/usr/bin/env sh
 
+### BEGIN VARS ###
+
 HOME_DIR=$HOME
-cd $HOME_DIR
-
-
 LOCAL_VERSION=$(/usr/local/share/plexmediaserver/Plex_Media_Server --version | sed 's/v//')
 LATEST_VERSION=$(w3m -dump https://plex.tv/downloads/details/1\?build\=freebsd-x86_64\&channel\=16\&distro\=freebsd | awk -F"\"" '/Release id/ {print $4}')
 ARCH="FreeBSD-amd64"
@@ -14,73 +13,93 @@ PLEX_PATH="/usr/local/share"
 _SUDO="doas"
 WGET=$(which wget)
 
+### END VARS ###
+
+
+### BEGIN FUNCTIONS ###
+
+plex_update() {
+  echo -e "Download ..."
+	ARCHIVE="PlexMediaServer-${LATEST_VERSION}-${ARCH}.tar.bz2"
+	wget https://downloads.plex.tv/plex-media-server-new/${LATEST_VERSION}/freebsd/PlexMediaServer-${LATEST_VERSION}-${ARCH}.tar.bz2 > /dev/null 2>&1
+	echo -e "----"
+	
+	echo -e "Decompress ..."
+	tar -xvf ${ARCHIVE} > /dev/null 2>&1
+	mv ${PLEX_TMP} ${PLEX_DIR}
+	rm PlexMediaServer-${LATEST_VERSION}-${ARCH}.tar.bz2
+	echo -e "----"
+
+	if [ "${PROCESS}" -eq "0" ] ; then	
+	  echo -e "service stop ..."
+		$_SUDO service plexmediaserver stop >/dev/null 2>&1
+		echo -e "----"
+	fi
+	echo -e "update in progress ..."
+	cd ${PLEX_DIR}
+	ln -s "Plex Media Server" Plex_Media_Server
+  }
+
+plex_replace_old() {
+	$_SUDO rm -rf ${PLEX_DIR_OLD} # Remove previous old dir
+	$_SUDO mv ${PLEX_DIR} ${PLEX_DIR_OLD} # Move current dir to old dir, to rollback in case of issue with upgrade process
+	$_SUDO mv ${HOME_DIR}/${PLEX_DIR} ${PLEX_PATH}/
+	echo -e "----\nservice start ..."
+	$_SUDO service plexmediaserver start > /dev/null 2>&1
+  }
+
+# if previous old dir is missing
+plex_replace() {
+  $_SUDO mv ${PLEX_DIR} ${PLEX_DIR_OLD}
+	$_SUDO mv ${HOME_DIR}/${PLEX_DIR} ${PLEX_PATH}/
+	echo -e "service start ..."
+	$_SUDO service plexmediaserver start >/dev/null 2>&1
+  }
+
+### END FUNCTIONS ###
+
+### BEGIN SCRIPT ###
+
 if test ! -f $WGET ; then
   echo -e "You need to have wget installed before using this update script" 
   exit 0
   else
-if test ! -z $LATEST_VERSION ; then
-
-if [ $USER == "root" ];	then 
-	echo -e "Avoid running this script as root\nExiting ..."
+  if test ! -z $LATEST_VERSION ; then
+    if [ $USER == "root" ];	then 
+    echo -e "Avoid running this script as root\nExiting ..."
 else
 
+cd $HOME_DIR
 
 service plexmediaserver status >/dev/null 2>&1
 PROCESS=$?
 
-if [ "$LOCAL_VERSION" == "$LATEST_VERSION" ]
-	then
-		echo -e "Running version : $LOCAL_VERSION\nLatest release  : $LATEST_VERSION\n---\nYou already have the latest version"
-	else
-		echo -e "Running version : $LOCAL_VERSION\nLatest release  : $LATEST_VERSION\nUpdate available, proceed ? (Y/n)"
-	read ANSWER
+    if [ "$LOCAL_VERSION" == "$LATEST_VERSION" ]; then
+		    echo -e "Running version : $LOCAL_VERSION\nLatest release  : $LATEST_VERSION\n---\nYou already have the latest version !"
+	    else
+		    echo -e "Running version : $LOCAL_VERSION\nLatest release  : $LATEST_VERSION\nUpdate available, proceed ? (Y/n)"
+	    read ANSWER
 
-	case ${ANSWER} in 
-	n)
-		exit 0
-		;;
+      case ${ANSWER} in 
+	      n)
+		      exit 0
+		      ;;
+	      *)
+		      plex_update
+          ;;
+	    esac
 
-	*)
-		echo -e "Download ..."
-		ARCHIVE="PlexMediaServer-${LATEST_VERSION}-${ARCH}.tar.bz2"
-		wget https://downloads.plex.tv/plex-media-server-new/${LATEST_VERSION}/freebsd/PlexMediaServer-${LATEST_VERSION}-${ARCH}.tar.bz2 > /dev/null 2>&1
-		echo -e "----"
-	
-		echo -e "Decompress ..."
-		tar -xvf ${ARCHIVE} > /dev/null 2>&1
-		mv ${PLEX_TMP} ${PLEX_DIR}
-		rm PlexMediaServer-${LATEST_VERSION}-${ARCH}.tar.bz2
-		echo -e "----"
+      cd ${PLEX_PATH}
+	      if [ -d ${PLEX_DIR_OLD} ]; then 
+	        plex_replace_old
+        else 
+	        plex_replace
+	      fi
+    fi
+  fi
 
-	if [ "${PROCESS}" -eq "0" ] ; then	
-		echo -e "service stop ..."
-		$_SUDO service plexmediaserver stop
-		echo -e "----"
-	fi
-		echo -e "update in progress ..."
-		cd ${PLEX_DIR}
-		ln -s "Plex Media Server" Plex_Media_Server
-		;;
-	esac
-
-	cd ${PLEX_PATH}
-	if [ -d ${PLEX_DIR_OLD} ]
-		then 
-			$_SUDO rm -rf ${PLEX_DIR_OLD} # Remove previous old dir
-			$_SUDO mv ${PLEX_DIR} ${PLEX_DIR_OLD} # Move current dir to old dir, to rollback in case of issue with upgrade process
-			$_SUDO mv ${HOME_DIR}/${PLEX_DIR} ${PLEX_PATH}/
-			echo -e "----\nservice start ..."
-			$_SUDO service plexmediaserver start
-		else # if previous old dir is missing
-			$_SUDO mv ${PLEX_DIR} ${PLEX_DIR_OLD}
-			$_SUDO mv ${HOME_DIR}/${PLEX_DIR} ${PLEX_PATH}/
-			echo -e "service start ..."
-			$_SUDO service plexmediaserver start
-		fi
-	fi
-fi
-else
-  echo -e "Unable to fetch latest PMS version" # Network error ?
-  exit 1
-fi
+  else
+    echo -e "Unable to fetch latest PMS version" # Network error ?
+    exit 1
+  fi
 fi
